import { useTranslation } from 'react-i18next';
import { FileCode, Globe, Layers, Settings } from 'lucide-react';

export function XMLContent() {
    const { t } = useTranslation();

    return (
        <div className="space-y-12">
            <section>
                <h2 className="text-3xl font-bold mb-6 flex items-center gap-2">
                    <FileCode className="w-8 h-8 text-primary" />
                    The Ultimate Guide to XML Formatting and Structural Integrity
                </h2>
                <p>
                    XML, or Extensible Markup Language, has been a cornerstone of data representation and exchange for decades. Unlike its cousin HTML, which is focused on how data looks, XML is purely about what the data is. By using a system of custom tags, XML allows developers to create self-describing data structures that can be understood by both humans and machines across disparate systems.
                </p>
                <p>
                    Despite the rise of JSON, XML remains essential in many domains, including enterprise software, configuration management (like Android's AndroidManifest.xml or Maven's pom.xml), and document formats (like Microsoft Word's .docx). However, the strict nature of XML means that even a single missing closing tag or an improperly nested element can render the entire document invalid. This is where a professional XML Formatter and Beautifier becomes an indispensable tool in a developer's arsenal.
                </p>

                <h3>Understanding the Strictness of XML</h3>
                <p>
                    XML is a markup language with very rigid rules. A document is only "well-formed" if it adheres to these fundamental principles:
                </p>
                <ul>
                    <li><strong>Root Element:</strong> Every XML document must have exactly one root element that contains all other elements.</li>
                    <li><strong>Closing Tags:</strong> All tags must be closed. While HTML allows some shorthand, XML requires explicit closing tags like <code className="bg-secondary px-1 rounded">&lt;/element&gt;</code> or self-closing tags like <code className="bg-secondary px-1 rounded">&lt;element /&gt;</code>.</li>
                    <li><strong>Case Sensitivity:</strong> XML tags are case-sensitive. <code className="bg-secondary px-1 rounded">&lt;Address&gt;</code> and <code className="bg-secondary px-1 rounded">&lt;address&gt;</code> are treated as completely different elements.</li>
                    <li><strong>Proper Nesting:</strong> Elements must be closed in the reverse order they were opened. You cannot have "crossed tags" like <code className="bg-secondary px-1 rounded">&lt;b&gt;&lt;i&gt;content&lt;/b&gt;&lt;/i&gt;</code>.</li>
                </ul>
                <p>
                    Our XML formatter automatically checks for these rules while beautifying your code. If your XML is not well-formed, our tool will provide feedback, helping you locate the exact line where the structure fails.
                </p>

                <h3>Why You Need a Dedicated XML Beautifier</h3>
                <p>
                    Raw XML, especially when generated by machines, is often "compacted" or "minified" to save space. While this is great for performance, it is a nightmare for developers trying to read or edit the code. Beautifying XML involves:
                </p>
                <ol>
                    <li><strong>Hierarchical Indentation:</strong> By adding consistent whitespace (usually 2 or 4 spaces), the relationship between parent and child elements becomes visually obvious.</li>
                    <li><strong>Attribute Alignment:</strong> Complex elements with many attributes (common in SOAP or configuration files) are much easier to read when the attributes are organized clearly.</li>
                    <li><strong>Namespace Management:</strong> XML namespaces (using <code className="text-primary italic">xmlns</code>) are critical for avoiding name collisions. A good formatter preserves these definitions and makes them readable.</li>
                    <li><strong>Comments and CDATA:</strong> Preserving internal documentation and CDATA blocks (where raw text/code is stored) is essential for maintaining the context of the data.</li>
                </ol>

                <h3>Advanced XML Features: Declarations and DTDs</h3>
                <p>
                    A professional XML document usually starts with a declaration: <code className="bg-secondary px-1 rounded">&lt;?xml version="1.0" encoding="UTF-8"?&gt;</code>. This line tells parsers which version of XML to use and how to interpret the character data. Our formatter understands these instructions and ensures they remain at the very top of your document.
                </p>
                <p>
                    Furthermore, XML documents often reference a DTD (Document Type Definition) or an XSD (XML Schema Definition). These external files act as a "blueprint," defining what tags are allowed and what data types they should contain. While our online formatter focuses on beautification and well-formedness, it serves as the perfect first step before performing full schema validation.
                </p>

                <div className="bg-secondary/20 p-8 rounded-2xl border border-border my-8">
                    <h4 className="text-xl font-bold mb-4 flex items-center gap-2 text-gradient">
                        <Globe className="w-6 h-6 text-primary" />
                        Cross-Platform Data Exchange
                    </h4>
                    <p className="mb-0">
                        XML's greatest strength is its platform independence. Because it is simple text, it can be sent from a Windows server to a Linux client, parsed by a Python script, and displayed in a web browser without any translation issues. This makes it the ideal choice for legacy system integration and complex business-to-business (B2B) communications.
                    </p>
                </div>

                <h3>Best Practices for XML Development</h3>
                <p>
                    To ensure your XML files are maintainable and scalable, follow these tips:
                </p>
                <ul>
                    <li><strong>Avoid Deep Nesting:</strong> Just like and tree-like structure, too much depth makes parsing slow and reading difficult. Aim for a balanced hierarchy.</li>
                    <li><strong>Use Attributes for Metadata:</strong> Use child elements for actual data and attributes for metadata (data about the data). For example, <code className="bg-secondary px-1 rounded">&lt;price currency="USD"&gt;99.99&lt;/price&gt;</code>.</li>
                    <li><strong>Comment Generously:</strong> Use <code className="bg-secondary px-1 rounded">&lt;!-- --&gt;</code> to explain complex sections or technical decisions within your XML.</li>
                    <li><strong>Validate Frequently:</strong> Always use a formatter and validator like this one during your development process to catch structural issues early.</li>
                </ul>

                <h3>XML Frequently Asked Questions</h3>
                <div className="grid gap-4 mt-6">
                    <details className="group border border-border rounded-lg p-4 bg-secondary/5">
                        <summary className="font-semibold cursor-pointer list-none flex justify-between items-center">
                            What is CDATA in XML?
                            <span className="transition-transform group-open:rotate-180">▼</span>
                        </summary>
                        <p className="mt-3 text-sm text-muted-foreground">
                            CDATA blocks are used to include blocks of text that would otherwise be interpreted as markup. For example, if you need to store a snippet of HTML or JavaScript inside XML, you wrap it in <code className="bg-secondary px-1 rounded">&lt;![CDATA[ ... ]]&gt;</code> so the XML parser ignores any angle brackets inside.
                        </p>
                    </details>
                    <details className="group border border-border rounded-lg p-4 bg-secondary/5">
                        <summary className="font-semibold cursor-pointer list-none flex justify-between items-center">
                            Can XML have empty elements?
                            <span className="transition-transform group-open:rotate-180">▼</span>
                        </summary>
                        <p className="mt-3 text-sm text-muted-foreground">
                            Yes. In XML, you can represent an empty element in two ways: <code className="bg-secondary px-1 rounded">&lt;item&gt;&lt;/item&gt;</code> or the shorthand <code className="bg-secondary px-1 rounded">&lt;item/&gt;</code>. Both are technically correct and treated identically by parsers.
                        </p>
                    </details>
                </div>
            </section>
        </div>
    );
}
